### ISSUE TITLE
Issue with initialising 2 serial objects out of init method 

### ISSUE THREAD

**Issue by dineshb302** [pezi/flutter_pi_sensor_tester#1]
When I try to initialise isolate like this, it works fine and 2 serial connections are created and I am able to get the data 

```
   TextEditingController _controller = TextEditingController();
  late StreamController<TaskResult> isolateStreamController;
  IsolateWrapper isolateWrapper1 = CozIRisolate('cozir', false);
  late StreamController<TaskResult> isolateStreamController2;
  IsolateWrapper isolateWrapper2 = GPIOisolate('gpio', false);
 void initState() {
        super.initState();
        isolateStreamController = startIsolate(isolateWrapper1);
        isolateStreamController2 = startIsolate(isolateWrapper2);
    
        isolateStreamController.stream.listen((event) {
          print('event- ${event.data}');
        });
    
        isolateStreamController2.stream.listen((event) {
          print('event- ${event.data}');
        });
        uartService.startListening();
        uartService.dataStream.listen((data) {
          setState(() {
            receivedMessages.add(data);
          });
        });
      }
```

But when I try to initialise the isolates out of init() method on button click like below, only one serial connection is successful, if I try to do 2 connection the app crashes.

While doing this I can see isolates are created but it crashes while opening the 2nd serial port. 

If i do only one at a time on button click it works fine.

if I try to do on different button action also it fails.

`void _startIsolate() async{
  try {
      // Start the first isolate and listen to its stream
      isolateStreamController = startIsolate(isolateWrapper1);
      isolateStreamController.stream.listen((event) {
        print('Listener event 1 - ${event.data}');
      });

      Start the second isolate and listen to its stream
      isolateStreamController2 = startIsolate(isolateWrapper2);
      isolateStreamController2.stream.listen((event) {
        print('Listener event 2 - ${event.data}');
      });
    } catch (e) {
      print('Error starting isolate $e');
    }
  }`
  
  Can you please guide me here, how can I spawn isolate on button action and create different serial connections, I need to collate 2 sensor data.

**Comment by dineshb302** [comment]
I have added a button to close the isolate, when I close the isolate and again try to restart the isolate the application fails again. So basically my hunch is once I have the serial object initialised, on dispose it is not getting de initialised also. 
So basically 2 issues - 
- creating 2 serial connections in non init method
- re creating serial connection

**Comment by pezi** [comment]
Probably the known error mentioned in the readme,

`Known errors: Demo crashes in hardware mode after closing a demo and open the next demo. There is a problem with the re-init of the periphery C-library in context of the isolates. Investigations are ongoing.`

**Comment by dineshb302** [comment]
Thanks for quick reply @pezi.  
So in my case I am able to spawn 2 isolates from init method on the displaying widget. But from any other method on the widget I can create just one, creating other crashes the application. 
- So for starting multiple isolates do I need to start the isolate from init only ? 
- If the the serial connection crashes in isolate, is there a workaround to restart it ? 

It will help if you could please share some pointers or workarounds on how I can have more control on starting/stopping Isolate with serial connections to have more control over sensors. Thanks.

**Comment by pezi** [comment]
I found a temporal fix for my crash scenario - start HW demo, stop HW demo,  start HW demo

1. Installed latest https://github.com/vsergeev/c-periphery as a shared lib
2. add useSharedLibrary() inside each main/isolate code - before using any dart_periphery code 
3. export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH  
4. flutter-pi --release your_project

I  must dig into, why the prebuild libs are not working.

**Comment by pezi** [comment]
I found the real reason for the crash. Dart periphery ships the needed libs and creates a tmp lib during it's usage:
e.g. arm7: /tmp/libperiphery_arm.so

But an isolate  is due his nature not aware of any configuration outside. The next isolate tries to re-create this tmp .so file which is in use, full crash.

add simple `reuseTmpFileLibrary(true);` inside each main/isolate code - before using any dart_periphery code

I will improve dart_periphery detect this problem.

**Comment by dineshb302** [comment]
Thanks @pezi for the info, I will try adding `reuseTmpFileLibrary(true);` and see if it works for me.

**Comment by pezi** [comment]
I updated this project with the `reuseTmpFileLibrary(true)` fix.

This code, which writes the c-periphery lib into the tmp dir, crashs without any change to catch any error/exception. It seems that the loaded lib is memory mapped, or a similar mechanism is active - but writing the lib again while an other isolate uses this lib isn't a good idea.

``` dart
 try {
          file.createSync(recursive: false);
          final decodedBytes = base64Decode(base64EncodedLib);
          // crashes, calling this line again
          file.writeAsBytesSync(decodedBytes);
        } on Error catch (e) {
          throw LibraryException(
              LibraryErrorCode.errorWritingLib, e.toString());
        } on Exception catch (e) {
          throw LibraryException(
              LibraryErrorCode.errorWritingLib, e.toString());
        }
```

An an alternative solution, you can use: `void loadLibFromFlutterAssetDir(bool load) `
See: https://github.com/pezi/dart_periphery?tab=readme-ov-file#flutter-pi

**Comment by dineshb302** [comment]
@pezi sorry I did't get exactly where do you want me to add `void loadLibFromFlutterAssetDir(bool load)`.
Can you please share some some sample code or something I can refer to get more clarity on it's use.

**Comment by pezi** [comment]
For the flutter-pi you can copy the correct CPU arch 

* CpuArchitecture.ARM → [libperiphery_arm.so](https://github.com/pezi/dart_periphery/raw/main/lib/src/native/libperiphery_arm.so)
* CpuArchitecture.ARM64 → [libperiphery_arm64.so](https://github.com/pezi/dart_periphery/raw/main/lib/src/native/libperiphery_arm64.so)

into the asset directoy. And if you use  ` loadLibFromFlutterAssetDir(true);` Dart periphery would load the right lib from the asset direcotry.

`flutter-pi asset_dir`

dart_periphery gets the asset_dir from the CLI-env and loads e.g  /absolute_path/asset_dir/libperiphery_arm.so without creating a temporary .so lib.  But you must call loadLibFromFlutterAssetDir(true) for each isolate.

BTW: For the next dart_periphery version the isolate problem is fixed.

**Comment by pezi** [comment]
You can easly use the fix - checkout the newest version of Dart periphery

```
git clone git@github.com:pezi/dart_periphery.git
cd dart_periphery
git checkout ps/0.9.7
```
pubspec.yaml

```
  dart_periphery: 
    path: ../dart_periphery (path to the local dart_periphery version)
```
